on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  backslash_scan_job:
    runs-on: ubuntu-latest
    name: Backslash scan
    steps:
      - name: Backslash scan step
        id: bscan
        uses: backslash-security/scan-action@before
        with:
          authToken: ${{ secrets.AUTH_TOKEN }} 
          githubToken: ${{ secrets.PAT }}
          ignoreBlock: false
          prScan: true
